MINT:
  n_limit: 3
  cooling_factor: 2
nova:
  dimensions:
    d_model: 1024
    dff: 4096
    num_heads: 32
    num_transformers: 8
  run_specs:
    dropout_rate: 0.5
    num_samples: 15
    top_p: 0.8
    temperature: 0.01
    layerdrop: 0.2
  training_specs:
    learning_rate: 0.01
    num_epochs: 10
    num_samples: 1
