encoder:
  n_limit: 3
nova:
  dimensions:
    d_model: 1024
    dff: 4096
    num_heads: 32
    num_transformers: 8
  run_specs:
    dropout_rate: 0.5
    num_samples: 15
    p: 0.8
    temperature: 0.01
  training_specs:
    learning_rate: 0.01
    num_epochs: 10
    num_samples: 1
