# nova model hyperparameters
nova:
  # model dimension parameters
  dimensions:
    d_model: 1024
    num_heads: 32
    num_transformers: 8
    dff: 4096
  # specifications on forward pass performance
  run_specs:
    dropout_rate: 0.5
    temperature: 0.01
    p: 0.8
    num_samples: 15
  # training specifications
  training_specs:
    learning_rate: 0.01
    num_epochs: 10
    num_samples: 1
# encoder hyperparameters
encoder:
  n_limit: 6  # token length limit
  n_combos: 0  # total number of token combinations
